---
title: "EDA_sentiment_stanford"
author: "Sandar Felicity Lim"
date: "5/20/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(caret)
library(MASS)
library(mclust)
library(lattice)
library(traj)
library(kml)
library(reshape)
```

# Note
20/5/2018: With super small amount of stories (n=100). 
Will run the analysis with larger dataset later




##data
```{r data}
dat<-read.table("/Users/sandar/nlu-project2/data/Stanford_highscores.txt", sep=",", col.names = c("title","s1","s2","s3","s4","Class"))
head(dat)
```
##legend
Very sad = 0
sad = 1
neutral = 2
happy = 3
very happy = 4

##stratified sampling
```{r sampling}
set.seed(123)
train.index <- createDataPartition(dat$Class, p = .7, list = FALSE)
train <- dat[ train.index,]
test  <- dat[-train.index,]
test2 <- test[,-6]
```

##Check 1: Linear Discriminant Analysis
```{r lda, echo=TRUE}
m1 <- lda(Class~., data = train)
m1
test$predict <- predict(m1,newdata=test2)$class

classError(test$predict,test$Class)
```



##Check 2: Correlations
```{r cor, echo=TRUE}
cor1<-as.matrix(cor(dat))
cor2<-cor(filter(dat,Class==3|4))
cor3<-cor(filter(dat,Class==0|1))

levelplot(cor1)
#happy ending: 
levelplot(cor2)
#sad ending:
levelplot(cor3)
```



##EDA 1: Longitudinal clustering
```{r lclust, echo=TRUE}
comp.dat <- data.frame(ID=seq(1,100,1), dat )
comp.time <- data.frame(ID=seq(1,100,1), title =0, s1= 1, s2=2, s3=3,s4=4, Class=5)
s1 = step1measures(comp.dat, comp.time, ID = TRUE)
s2 = step2factors(s1)
s2 = step2factors(s1)
step3clusters(s2,  nclusters = NULL,nstart=50,
              criteria = "ccc", forced.factors = NULL)
#4 clusters look good
s3 = step3clusters(s2,  nclusters = 4)
plot(s3)
```


##EDA 2:  K-Means for Longitudinal Data
```{r kml, echo=TRUE, warning=FALSE}
colnames(comp.dat)<- c("ID","s0", "s1","s2","s3","s4","s5")
dat.long<- melt(comp.dat, idvar="ID", measure.vars =c("s0", "s1","s2","s3","s4","s5") )
cld1 <-clusterLongData(traj=dat,idAll = seq(1,100,1), time=c(1,2,3,4,5,6))
kml(cld1,3,2)
```
